site_name: packer
site_author: Andrew Thomas Lee
site_url: https://packer.andrewlee.cloud
repo_url: https://github.com/andrewthomaslee/packer
repo_name: andrewthomaslee/packer

nav:
  - Home: index.md
  - Flake Parts:
      - Overview: flake-parts/index.md
      - Default: flake-parts/default.md
      - Dev Shells: flake-parts/devShells.md
      - Apps:
          - Overview: flake-parts/apps/index.md
      - Packages:
          - Overview: flake-parts/packages/index.md
      - NixOS Modules:
          - Overview: flake-parts/nixosModules/index.md

plugins:
  - glightbox
  #- info # only useful for debugging
  - offline
  - search
  - tags

theme:
  font: false

  language: en

  name: material

  icon:
    repo: fontawesome/brands/github

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: blue
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference